DIGI_CLOUD_URL  =           "https://console.digicloud.dev/"
CHROME =                    "Chrome"
LOGIN_PG =                  "class=auth"
MAIL_INPUT_BOX =            "id:email"
MAIL_VALUE =                "newsha.amiri@digikala.com"
PASS_INPUT_BOX =            "id:password"
PASS_VALUE =                "Newsh@@4560"
LOGIN_BUTTON =              "//*[@id='app']/div[2]/div/main/div[2]/form/button"
INCREASE_POPUP =            "Price update notice"
GOT_IT_BTN =                " Got it "
HOME_PAGE =                 "//*[@id='app']/div[2]/main/div[2]/div[1]"
SERVICE_DROPDOWN =          "//*[@id='app']/div[2]/header/nav/div/div[2]/div[1]/div[1]"
REGION_SELECTOR =           "class=dropdown__toggle region-selection__toggle"
REGION_NAME =               " ir-vanak-plaza "
DROPDOWN_DESCRIPTION =      "class='header__services-dropdown-menu-intro text-center'"
CLOUD_COMPUTING =           "//*[@id='app]/div[2]/header/nav/div/div[2]/div[1]/div[2]/ul/li[1]/span[1]"
